USE [master]
GO
/****** Object:  Database [Coder]    Script Date: 7/26/2016 10:33:27 AM ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'Coder')
BEGIN
CREATE DATABASE [Coder]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Coder', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Coder.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Coder_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Coder_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
END

GO
ALTER DATABASE [Coder] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Coder].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Coder] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Coder] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Coder] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Coder] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Coder] SET ARITHABORT OFF 
GO
ALTER DATABASE [Coder] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Coder] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Coder] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Coder] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Coder] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Coder] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Coder] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Coder] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Coder] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Coder] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Coder] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Coder] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Coder] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Coder] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Coder] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Coder] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Coder] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Coder] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Coder] SET  MULTI_USER 
GO
ALTER DATABASE [Coder] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Coder] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Coder] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Coder] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Coder] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Coder] SET QUERY_STORE = OFF
GO
USE [Coder]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [Coder]
GO
/****** Object:  Table [dbo].[__MigrationHistory]    Script Date: 7/26/2016 10:33:27 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[__MigrationHistory]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[__MigrationHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ContextKey] [nvarchar](300) NOT NULL,
	[Model] [varbinary](max) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK_dbo.__MigrationHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC,
	[ContextKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[Users]    Script Date: 7/26/2016 10:33:28 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Users]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[EmailId] [varchar](50) NOT NULL,
	[Password] [varchar](10) NOT NULL,
	[FirstName] [varchar](50) NULL,
	[LastName] [varchar](50) NULL,
	[CreatedOn] [datetime] NULL,
	[ModifiedOn] [datetime] NULL,
	[IsDeleted] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_Users_CreatedOn]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_CreatedOn]  DEFAULT (getdate()) FOR [CreatedOn]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Users__IsDeleted__267ABA7A]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Users] ADD  DEFAULT ((0)) FOR [IsDeleted]
END

GO
USE [master]
GO
ALTER DATABASE [Coder] SET  READ_WRITE 
GO
